### ISSUE TITLE
PDO mapping less than 8 bits

### ISSUE THREAD

**Issue by JuTakata** [robincornelius/libedssharp#102]
Hello,

I would like to map some bits from different sub indexes and it seems that this is not possible.

Object 3700 : 
Sub index 01 : VarA (3 bits)
Sub index 02 : VarB (2 bits)
Sub index 03 : VarC (2 bits)
...

And I would like to achieve : 
PDO1 Byte 0 Bit 0 = VarA (bit 0)
PDO1 Byte 0 Bit 1 = VarA (bit 1)
PDO1 Byte 0 Bit 2 = VarA (bit 2)
PDO1 Byte 0 Bit 3 = VarB (bit 0)
PDO1 Byte 0 Bit 4 = VarB (bit 1)
PDO1 Byte 0 Bit 5 = VarC (bit 0)
PDO1 Byte 0 Bit 6 = VarC (bit 1)
...

I loaded my existing EDS file from one other EDS editor (CANOpenNode html) which was configured like that and I get this error for each mapped sub indexes : 
![image](https://user-images.githubusercontent.com/20264907/30168420-a1795e02-93e9-11e7-97da-56f390b3ffc7.png)

The PDO mapping parameter is mapped as : 
![image](https://user-images.githubusercontent.com/20264907/30169338-666f0a34-93ec-11e7-9408-254a91844af4.png)

The PDO in the TX-PDO tab is mapped by one byte for each subindex : 
![image](https://user-images.githubusercontent.com/20264907/30168495-de67d1ea-93e9-11e7-935f-7676af065ed6.png)

Please is there a way to achieve this ? Or this is not supported yet ?

I am using the release v0.5.2.

Cheers
Julien

**Comment by s-fuchs** [comment]
Hi Julien,
CANopenNode does not support PDO mapping on the bit level (neither the editor).
The mapping function only allows per byte mapping: https://github.com/CANopenNode/CANopenNode/blob/master/stack/CO_PDO.c#L228

regards s-fuchs

**Comment by robincornelius** [comment]
Hi,

No the editor does not yet support this. The warning appears as its failed
to understand the currently set mapping so that is the correct thing to do
if the mapping is not understood.

I was not actually aware that you can do this with CanOpenNode as the PDO
mapping parameters in canopen node only allow one to set
index/subindex/datasize to be mapped. However it should be on the feature
list for the editor as other implementation do support this and it should
be able to read/write these eds files correctly.

Regards

Robin

**Comment by JuTakata** [comment]
@s-fuchs  Thank you for your answer you have right, I did not tried this yet I was modifiying my OD but I was requiring Domain variable so I just switched to Libedssharp before testing this.

@robincornelius Thank you for your answer, as @s-fuchs answered this is not supported by CanOpenNode, I thought it was and I will probably have to add this feature because this is in my customer specification.

Regards. Julien

**Comment by martinwag** [comment]
Usefullness depends on your requirement. Think about mapping a 401 output to a 401 input. With bit mapping you can assign any of the inputs to any output you want. With byte mapping, you only can assign groups of 8.
CANopenNode currently stores the mapping in an array, so making this bit-mappable means increasing array size from 8 to 64.

**Comment by JuTakata** [comment]
Hi

@martinwag I will modify my code to be byte mapping yes a bit-mapped approach would increase array size and I already have some memory issues.

I would like to add TIME_OF_DAY type to your EDS Editor but I am not very familiar with C#.
Should I open a new issue and describe the extra code required for .c and .h and someone could add this feature later ? 

Regards

Julien

**Comment by robincornelius** [comment]
Please yes, open a new issue for TIME_OF_DAY
