### ISSUE TITLE
TIME_OF_DAY data type

### ISSUE THREAD

**Issue by JuTakata** [robincornelius/libedssharp#104]
Hi,

I would like to suggest a new enhancement to support TIME_OF_DAY feature :
 
On CO_OD.h there should be the time of day typedef : 
`typedef timeOfDay_t  TIME_OF_DAY;`

And for CO_OD.c there should be brackets for each initializer : 
```/*2020*/ {0xeL, {0}, {0},```

I also added timeOfDay_t declaration to my CO_driver.c : 
```   
typedef union {
     unsigned long long ullValue;
     struct {
           unsigned long ms:28;
           unsigned reserved:4;
           unsigned days:16;
           unsigned reserved2:16;
     };
}timeOfDay_t;
```

I will suggest this to CANopenNode but I did not tested this yet.

Best regards

Julien

**Comment by kingd123** [comment]
JuTakata's request and suggested implementation, gets my vote too :-)

TIME_OF_DAY Data type is called for the CiA402 power drive profile, for Object 6406 'Motor calibration date'

It's the only CiA402 object that requires TIME_OF_DAY Data type mind !

**Comment by JuTakata** [comment]
Thank you for your support =)
