### ISSUE TITLE
 The v0.6-xdd-alpha-81-gb562769 version can not generate an EDS file.

### ISSUE THREAD

**Issue by xoduddk123** [robincornelius/libedssharp#106]
Hello.

There is something strange about using the Object Dictionary Editor.
I used https://github.com/robincornelius/libedssharp/releases/tag/0.6-xdd-2 in the release.
I could not create an EDS file in the Object Dictionary Editor using exe file and source code.

I've clicked "Save eds + xml + Export device", but I need to create an EDS file first.
![image](https://user-images.githubusercontent.com/10510127/31424585-f98dabcc-ae95-11e7-9324-3fc8d8ae33d6.png)

![image](https://user-images.githubusercontent.com/10510127/31424617-2071329a-ae96-11e7-86a8-8984095ff6ee.png)
But I have not found a way to save the EDS file.

I know that the version is pre-release, so I downloaded and built the source of https://github.com/robincornelius/libedssharp.
I built the source of the master and had an Open EDS, Save EDS button and was able to create an EDS file.![image](https://user-images.githubusercontent.com/10510127/31424759-f3b0de30-ae96-11e7-9384-fbfc8176dce1.png)

I'm sorry I do not have enough English. :)

Thanks!

**Comment by robincornelius** [comment]
Hi,

On XDD branch the eds and other file types are all under Save Device FIle, but now there are multiple types :-

![image](https://user-images.githubusercontent.com/159000/31431539-f5f046a2-ae6b-11e7-9c17-cbb6f2628c03.png)

Then you can select the type of file to save :-

![image](https://user-images.githubusercontent.com/159000/31431434-9fb648b8-ae6b-11e7-9e61-f258bf5e57c0.png)

The XDD branch supports more file types.

the actual xdd files are still a bit broken and i've not had time to look at them again

**Comment by xoduddk123** [comment]
Thank you for your kind reply.
I was able to see your answer and create an EDS file in the XDD branch.
![image](https://user-images.githubusercontent.com/10510127/31432939-e6887a30-aeb2-11e7-91ab-f08de825df30.png)

Thank you!
