### ISSUE TITLE
CANopenNode fails to compile due to OD_NMT_Startup.

### ISSUE THREAD

**Issue by xoduddk123** [robincornelius/libedssharp#109]
Hello.

Using CO_OD.h generated by libedssharp causes an error when compiling CANopen.c of CANopenNode.
![image](https://user-images.githubusercontent.com/10510127/32365247-729d4eea-c0bc-11e7-945c-4f9060150834.png)
The errorStatusBits error was resolved by recreating CO_OD.h.
However, the OD_NMTStartup error is slightly strange.

The CO_OD.h generated by libedssharp is defined as follows.
![image](https://user-images.githubusercontent.com/10510127/32365618-d5eb405a-c0bd-11e7-8305-25952ddc74d6.png)

In CANopen.c of CANopenNode, it is supposed to be used as OD_NMTStartup.
https://github.com/CANopenNode/CANopenNode/blob/533801574055c5dacf60fb6b18930c288336dce1/CANopen.c#L647-L654
![image](https://user-images.githubusercontent.com/10510127/32365361-f5542336-c0bc-11e7-9c9b-4d8f4f7fe45d.png)

So when compiling with CO_OD.h using libedssharp, an error occurs.
I first modified CANopen.c to fix the error.
But I think either libedssharp or CANopenNode need to be modified.

I modified libedssharp as shown below.
https://github.com/xoduddk123/libedssharp/commit/2268581331a0e703a78fec305ef8365f1bba46e5

I'm sorry I do not have enough English. :)

Best regards.
kwon

**Comment by martinwag** [comment]
Can this be the same problem as this one: https://github.com/robincornelius/libedssharp/issues/110#issuecomment-348989681 ?

I'm not on the xdd branch, and for me 

```
/*1f80 */
        #define OD_1f80_NMTStartup                                  0x1f80
```
is generated.

**Comment by robincornelius** [comment]
No its not the same bug. #110 was a hard coded string with a space in. This looks like a different hard coded string with a space,  its being solved my modifying the default profile file for NMTMaster.

**Comment by xoduddk123** [comment]
I confirmed that the source has been modified.
I am happy to contribute to the project.

Best regards.
kwon
