### ISSUE TITLE
Arrays of record sets not created correctly in CO_OD.h

### ISSUE THREAD

**Issue by robincornelius** [robincornelius/libedssharp#11]
They are a special case anyway but we currently have :-

*1600, Data Type: RPDOMappingParameter_t */
        #define OD_RPDOMappingParameter                             CO_OD_ROM.RPDOMappingParameter

/*1601, Data Type: RPDOMappingParameter_t */
        #define OD_RPDOMappingParameter                             CO_OD_ROM.RPDOMappingParameter

/*1602, Data Type: RPDOMappingParameter_t */
        #define OD_RPDOMappingParameter                             CO_OD_ROM.RPDOMappingParameter

/*1603, Data Type: RPDOMappingParameter_t */
        #define OD_RPDOMappingParameter                             CO_OD_ROM.RPDOMappingParameter

and if we compare to the reference implementation from CanOpenNode it looks like -

/*1600[4], Data Type: OD_RPDOMappingParameter_t, Array[4] */
      #define OD_RPDOMappingParameter                    CO_OD_ROM.RPDOMappingParameter

Nothing is actually broken in the existing code but the defines it is generating are messy and don't reflect its really an array. Not sure the best way to handle this as the whole handling of arrays of records is a odditity anyway and not strictly within the canopen spec but more to do with the CanOpenNode implementation.

**Comment by s-fuchs** [comment]
Maybe just print them once. You don't even have to indicate its an array at all, one can follow the define and just inspect CO_OD_ROM.RPDOMappingParameter direclty.
