### ISSUE TITLE
EDS file check fails.

### ISSUE THREAD

**Issue by xoduddk123** [robincornelius/libedssharp#110]
Hello.

I tried to create and use an EDS file with libedssharp.
I use LS's XBL-CMEA PLC.
![image](https://user-images.githubusercontent.com/10510127/32647225-8ecaabae-c633-11e7-97bf-b5e94cd5f715.png)
When registering EDS file created by libedssharp in software, registration fails as below.
![image](https://user-images.githubusercontent.com/10510127/32646768-7d30a33c-c631-11e7-9a14-2cf508650ff9.png)
"선택한 파일은 CANopen EDS파일이 아닙니다." 
 → "The file selected is not a CANopen EDS file."

I thought the problem was a software bug.
So I installed CANoe 10.0 (64bit) of Vector.
There is an EDS related tab called CANeds in the program.
![image](https://user-images.githubusercontent.com/10510127/32647016-b006a7a6-c632-11e7-8a16-02d99b3c104c.png)
I can load and check the EDS file from the CANeds tab.

If [Check] → [Check file] of CANeds is executed, the following error occurs.
![image](https://user-images.githubusercontent.com/10510127/32647076-f7cf7450-c632-11e7-88e6-6f1828b97a9f.png)

It says that "SupportedObjects" can not be found.
When i open the EDS file, it is "Supported Objects".
![image](https://user-images.githubusercontent.com/10510127/32647104-10cb6658-c633-11e7-9f01-55114f3e8122.png)
There is one space.

I have tested and the following modification will successfully check the EDS file.
https://github.com/xoduddk123/libedssharp/commit/c8eca9d277d76bd4d75c375db9f6b83e0c631cd6
![image](https://user-images.githubusercontent.com/10510127/32646995-932fee3a-c632-11e7-91f9-43d4dd2fda34.png)
![image](https://user-images.githubusercontent.com/10510127/32647140-3bb77988-c633-11e7-8d4e-a853b1fab4e3.png)
![image](https://user-images.githubusercontent.com/10510127/32647192-6b9f81fe-c633-11e7-94c5-39b25f4f4422.png)

I'm sorry I do not have enough English. :)

Best regards.
kwon

**Comment by robincornelius** [comment]
I can see what has happened. Looks like the XDD branch has a bug and is incorrectly putting a space in Supported Objects

**Comment by xoduddk123** [comment]
I confirmed that the source has been modified.
I am happy to contribute to the project.

Best regards.
kwon
