### ISSUE TITLE
XDD branch - exporting rrw / rww access type crashes editor

### ISSUE THREAD

**Issue by martinwag** [robincornelius/libedssharp#128]
Hi,

When I try to export XDD on a file that contains a OD entry with "rww" or "rwr" access type, the editor crashes.

I've tracked this down to CanOpenXDD.cs file, line

`AppLayer.CANopenObjectList.CANopenObject[count].accessType = (CANopenObjectListCANopenObjectAccessType)Enum.Parse(typeof(CANopenObjectListCANopenObjectAccessType), accesstype);`

where the cast from "rww" fails because that entry doesn't exist in XDD format. The same applies for the handling of sub-indexes.

I've had a look at the eds and xdd specification. They seem to differ in this use case:
- eds (6.6.3.2 Object description) saves access type and pdo map fields as they are inside the editor GUI (access type r, rw, ro, rrw, rwr and so on and mappable as true or false) 
- xdd (6.5.2.3.2 CANopenObject) splits this information into those two fields, where rrw and rww information is moved to the mappable field.

I've fixed this by adding something like this to index and subindex, but I think this is really ugly...

```
                //special handling for rrw / rww access type
                EDSsharp.AccessType accesstype = od.accesstype;
                PDOMappingType PDOtype = od.PDOtype;
                if (accesstype == EDSsharp.AccessType.rww) {
                    accesstype = EDSsharp.AccessType.rw;

                    // when optional, set it to the corresponding type
                    if (od.PDOtype == PDOMappingType.optional) {
                        od.PDOtype = PDOMappingType.RPDO;
                    }
                }
                if (accesstype == EDSsharp.AccessType.rwr) {
                    accesstype = EDSsharp.AccessType.rw;

                    // when optional, set it to the corresponding type
                    if (od.PDOtype == PDOMappingType.optional) {
                        od.PDOtype = PDOMappingType.TPDO;
                    }
                }
```

This is the entry I try to export in in CANopenNode XML format:

```
    <CANopenObject index="2205" name="LED output 8 bit" objectType="ARRAY" memoryType="RAM" dataType="0x05" accessType="rww" PDOmapping="optional" defaultValue="" subNumber="3" accessFunctionName="" disabled="false" TPDOdetectCOS="true">
      <description>This switches the LEDs on the front panel, depending on the setting in LED mode.</description>
      <CANopenSubObject subIndex="00" name="max sub-index" objectType="VAR" dataType="0x05" accessType="ro" PDOmapping="optional" defaultValue="2" TPDOdetectCOS="false" />
      <CANopenSubObject subIndex="01" name="LED red" objectType="VAR" dataType="0x05" accessType="rww" PDOmapping="optional" defaultValue="0" TPDOdetectCOS="false" />
      <CANopenSubObject subIndex="02" name="LED green" objectType="VAR" dataType="0x05" accessType="rww" PDOmapping="optional" defaultValue="0" TPDOdetectCOS="false" />
      <accessFunctionPreCode />
    </CANopenObject>
```

**Comment by robincornelius** [comment]
Oh awesome a incompatibility between the EDS and XDD standards, that is helpful.

Unfortunately we are going to need some kind of ugly fix then as it will have to translate this "special case" I'll start off with your code and see what else (if anything) can be done or if there are any other ways of dealing with this at all.

Thanks

**Comment by martinwag** [comment]
I've committed my hack to 1020d013dffda43520efca5c86c4045536388b97

**Comment by martinwag** [comment]
now 67fe444ba0eac3fd0c784e54efbef1ce22102bea

**Comment by robincornelius** [comment]
I've pulled in your commit and added the import fix as well, but not yet given it a good testing.

**Comment by martinwag** [comment]
Seems to work.
