### ISSUE TITLE
Unable to load EDS file

### ISSUE THREAD

**Issue by effemmeffe** [robincornelius/libedssharp#145]
When I try to open my EDS file I get this errors:
libEDSsharp.ParameterException: Unknown AccessType on1000
   in libEDSsharp.EDSsharp.parseEDSentry(KeyValuePair`2 kvp)
   in libEDSsharp.EDSsharp.loadfile(String filename)
   in ODEditor.ODEditor_MainForm.openEDSfile(String path)

Version 0.5.2

**Comment by robincornelius** [comment]
Can you see if version 0.6-XDD is any better it has a lot of improvements and also there has been much more work since 0.6 as well. So Please 1) Try 0.6, if this still fails send me the eds and i will try against the latest code

**Comment by effemmeffe** [comment]
I tried the 0.6 too and still no luck.
How do I send you the EDS file?

**Comment by robincornelius** [comment]
Please email to robin.cornelius@gmail.com

Thanks

**Comment by effemmeffe** [comment]
I managed to open it: I had some weird text in the File information section, after I removed it I could open the file.
Thanks, I'll close the issue.
