### ISSUE TITLE
 STRUCTURES FOR RECORD TYPE OBJECTS are not generated

### ISSUE THREAD

**Issue by robincornelius** [robincornelius/libedssharp#15]
The section STRUCTURES FOR RECORD TYPE OBJECTS in CO_OD.c is not currently populated so accessing record objects is producing undefined behaviour.

**Comment by s-fuchs** [comment]
Thanks for this fix. I noticed the absence of these structures, but had no problems compiling & running my project.
The output structures look almost like a 1:1 copy from old editor, good job.
