### ISSUE TITLE
Size of string/byte array inside an REC is not correct (CO_OD.h/c)

### ISSUE THREAD

**Issue by rubenverhoef** [robincornelius/libedssharp#150]
When i create an REC with an VISIBLE_STRING as subindex it will have an size of 1 in stead of the size of the string.

For example 0x2130SUB1, libedssharp makes this:
`{(void*)&CO_OD_RAM.time.string, 0x86, 0x1 }`
Which should be:
`{(void*)&CO_OD_RAM.time.string[0], 0x06, 30}` (see :https://github.com/CANopenNode/CANopenNode/blob/533801574055c5dacf60fb6b18930c288336dce1/example/CO_OD.c#L294)

The `0x06` -> `0x86` issue will be solved in #149

**Comment by robincornelius** [comment]
Yep fixed in git
