### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by kingd123** [robincornelius/libedssharp#151]
Hi Robin,

I'm just trialling your 0.7 release. Minor thing, but just to mention, still says 'Object Dictionary Editor v0.6-xdd-2.67-g6261921' in the titlebar, and in the generated CO_OD.c/h comment text header. And says '0.6-xdd-2-25-g654cd98' within the version.txt file.

Best regards,

David

**Comment by robincornelius** [comment]
Yea i saw that. I tagged on git hub, then uploaded a build but forgot
to pull the tags first. The Git ref should be ok but the tag ref is
wrong.

**Comment by robincornelius** [comment]
We are all upto date on version numbers on 0.8 release
