### ISSUE TITLE
Mutibyte value attribute

### ISSUE THREAD

**Issue by kingd123** [robincornelius/libedssharp#152]
Hi Robin,

I'm just trialling your 0.7 release. I've noticed, on delta'ing the generated CO_OD.c/h files, against those generated by the previous latest ODE release, that the multibyte value CO_ODA_MB_VALUE bit (0x80) is no longer set for text string objects or subobjects, within CO_OD.c. For example, some Before and After generated code, as below. Dunno if this is a ODE correction. Or an issue. Or the impact of. I can see though that the CO_ODA_MB_VALUE define is used by the CANopenNode stack source.

Before (.B and .C are text strings):

/*0x3000*/ const CO_OD_entryRecord_t OD_record3000[4] = {
           {(void*)&CO_OD_RAM.fooBar.maxSubIndex, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.fooBar.A, 0x0e, 0x1 },
           {(void*)&CO_OD_RAM.fooBar.B, 0x8e, 0x8c },
           {(void*)&CO_OD_RAM.fooBar.C, 0x86, 0x8c },

After:

/*0x3000*/ const CO_OD_entryRecord_t OD_record3000[4] = {
           {(void*)&CO_OD_RAM.fooBar.maxSubIndex, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.fooBar.A, 0x0e, 0x1 },
           {(void*)&CO_OD_RAM.fooBar.B, 0x0e, 0x8c },
           {(void*)&CO_OD_RAM.fooBar.C, 0x06, 0x8c },

Before:

const CO_OD_entry_t CO_OD[338] = {
:
{0x1008, 0x00, 0x86, 30, (void*)&CO_OD_RAM.fooBar},
:

After:

const CO_OD_entry_t CO_OD[338] = {
:
{0x1008, 0x00, 0x06, 30, (void*)&CO_OD_RAM.fooBar},
:
 
Below, for reference, how the CO_SDO_OD_attributes_t enums are defined, in CO_SDO.h:

/**
 * Object Dictionary attributes. Bit masks for attribute in CO_OD_entry_t.
 */
typedef enum{
    CO_ODA_MEM_ROM          = 0x0001U,  /**< Variable is located in ROM memory */
    CO_ODA_MEM_RAM          = 0x0002U,  /**< Variable is located in RAM memory */
    CO_ODA_MEM_EEPROM       = 0x0003U,  /**< Variable is located in EEPROM memory */
    CO_ODA_READABLE         = 0x0004U,  /**< SDO server may read from the variable */
    CO_ODA_WRITEABLE        = 0x0008U,  /**< SDO server may write to the variable */
    CO_ODA_RPDO_MAPABLE     = 0x0010U,  /**< Variable is mappable for RPDO */
    CO_ODA_TPDO_MAPABLE     = 0x0020U,  /**< Variable is mappable for TPDO */
    CO_ODA_TPDO_DETECT_COS  = 0x0040U,  /**< If variable is mapped to any PDO, then
                                             PDO is automatically send, if variable
                                             changes its value */
    CO_ODA_MB_VALUE         = 0x0080U   /**< True when variable is a multibyte value */
}CO_SDO_OD_attributes_t;

Best regards,

David

**Comment by robincornelius** [comment]
Hi,

The multi byte flag was being set incorrectly for string objects, it should
only be used on objects where the fundamental data type is more than one
byte. a VISIBLE_STRING is an array of VISIBLE_CHAR so it should not be set.
This was also causing some string lengths to be reported incorrectly.  I
believe it is now correct and if you compare a string object to the
original example CO_OD.c/h files they now match on VISIBLE_STRING types.

**Comment by kingd123** [comment]
Ah, cool, a fix, great. I'll see in due course how that affects eg SDO read/write of strings.
