### ISSUE TITLE
Command button not visable

### ISSUE THREAD

**Issue by trojanobelix** [robincornelius/libedssharp#154]
![image](https://user-images.githubusercontent.com/15106425/52119241-c8b6bb00-2618-11e9-820d-274a15027ef9.png)

Hi Robin,

I am trying the 0.7 on the Xdd branch. I have the problem, that I can not see the command button to save changes in the OD .  I use VS2017 to compile the source code.

**Comment by robincornelius** [comment]
What screen size are you using?

Ah i know whats happened, the extra field as pushed it just out of reach at
the bottom. I'll fiddle with the layout

**Comment by robincornelius** [comment]
AH no its not that, on mine i can shrink/grow the window and the
description field will change size and the  subindex list box changes size
as well and it all fits any size down to quite a small display. Wonder why
its working differently for you.. if you resize the window (drag it around)
does it fix itsself?

**Comment by trojanobelix** [comment]
Nothing special. 1920x1080. External IIYAMA monitor on a HP notebook. 

Microsoft Windows 7 Professional 	6.1.7601 Service Pack 1 Build 7601
Hewlett-Packard HP ProBook 6570b 
Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz, 2501 MHz, 2 Kern(e), 4 logische(r) Prozessor(en)
BIOS	Hewlett-Packard 68ICE Ver. F.42, 20.05.2013

**Comment by trojanobelix** [comment]
No. I can resize and maximize, but the button is always mostly  pushed out of reach. Always on the position you see on the picture.

**Comment by trojanobelix** [comment]
Small 
![image](https://user-images.githubusercontent.com/15106425/52120039-6e6b2980-261b-11e9-840c-bcf93b3868c0.png)

Maximized
![image](https://user-images.githubusercontent.com/15106425/52120069-804ccc80-261b-11e9-9b1a-bce77a10bd9e.png)

**Comment by trojanobelix** [comment]
Not sure, but I think it changed with my change to the XDD branch some month ago.
I just "use" the software and forgot to report it.

**Comment by robincornelius** [comment]
I've put the controls in a container and adjusted the anchor, see if that
helps

**Comment by trojanobelix** [comment]
Okay. The button is visible now.
But I do not get a warning when leaving the window with data changed. The button does not change to red background on data change.

**Comment by robincornelius** [comment]
Ah yea, putting the controls inside a group box caused them to not be added
to the changed notification. Should be fixed.

**Comment by trojanobelix** [comment]
Perfect now. 
Thanks a lot! 

Have a nice weekend.
