### ISSUE TITLE
PDO mapping not restored from eds file

### ISSUE THREAD

**Issue by trojanobelix** [robincornelius/libedssharp#155]
Hi Robin, 
when saving the object file as eds with optional PDO mapping enabled, this configuration is not restored when reopen that eds file

E.g. custom object 2310h:
create this object and  set PDO MAP to "optional"
Save as EDS
It is saved in the eds file.
Close the file
Open the file again
 PDO MAP is erroneously set to "no" instead using the saved value "optional"

**Comment by robincornelius** [comment]
Seems fine on latest XDD head so closing, feel free to reopen if its not
