### ISSUE TITLE
Bug: Unable to save c file with different file name

### ISSUE THREAD

**Issue by trojanobelix** [robincornelius/libedssharp#157]
The c file is saved as CO_OD.c, even if you change the file name in the explorer window. 

Regardless if you change the name by typing a new filename or choosing a different file on the directory view.

To reproduce:
1. Place an file "test1.c" in a directory.
2. export c file
3. choose "test1.c" in the directory view.
4. CO_OD.c is saved. Not "test1.c"

To reproduce 2:
1. export c file
2. type "test2.c" as new file name 
4. CO_OD.c is saved. Not "test2.c"

**Comment by martinwag** [comment]
I think this is the same as my bug https://github.com/robincornelius/libedssharp/issues/138

**Comment by trojanobelix** [comment]
Yes that's right. Sorry, missed it.
