### ISSUE TITLE
[EDS] StorageLocation why is the ; in front of it?

### ISSUE THREAD

**Issue by rubenverhoef** [robincornelius/libedssharp#159]
When exporting an EDS file it will give you
`;StorageLocation=xxx`
Why is the ; before this line? My program using: https://github.com/christiansandberg/canopen does ignore this variable because of this.

**Comment by robincornelius** [comment]
Hi,

the ; makes it a comment and StorageLocation is not part of the actual EDS
specification but its very useful to have so we add it as a comment. It is
correct for all other programs to ignore this.

Hope this helps

**Comment by rubenverhoef** [comment]
Okay thanks for the explanation.
