### ISSUE TITLE
"Memory Type" selector and "Save Changes" not visible.

### ISSUE THREAD

**Issue by ABH10** [robincornelius/libedssharp#163]
I am trying to use the pre-compiled release 0.7 on Windows 10. When using the "Object Dictionary" tab I cannot see some of the bottom controls in the window. If I resize the window the "Description" field scales, but the bottom controls remain "hidden" outside the window.  
![libedssharp_issue](https://user-images.githubusercontent.com/22498335/58686236-8dd25300-837e-11e9-905c-1a64b06cc1ca.png)

**Comment by HeJiaRu** [comment]
![image](https://user-images.githubusercontent.com/54353375/63580521-93c78100-c5c7-11e9-9d6d-968ede5583ae.png)

same on Windows 7

**Comment by robincornelius** [comment]
should be ok on 0.8 release now
