### ISSUE TITLE
Add Command Line Options for File IO and Conversion

### ISSUE THREAD

**Issue by Bartimaeus-** [robincornelius/libedssharp#171]
It would be nice to have the ability to generate the CANopenNode CO_OD files via the command line (pass in the .EDS file name and output file name). Even if it were a separate executable from the GUI, it would be nice to use some of the libedssharp features for file conversion from the command line.

**Comment by robincornelius** [comment]
Hi, should be no problems. the main GUI is split from the core anyway and eveything in the core lib is there to open eds/xml/xdd and generate CO_OD files (or any other formats should they be added). I just need some time to do some more work on this and work through these features/bugs

**Comment by robincornelius** [comment]
Added a new project to git that invokes libedssharp from a command line application, it accepts eds/xml or xdd as input files and produces a CO_OD.c/h (name choosable) as an output file.
