### ISSUE TITLE
bug: accessType=cons in eds?

### ISSUE THREAD

**Issue by s-fuchs** [robincornelius/libedssharp#23]
I think it should be "accessType=const". I could be the a result of your "nasty workaround" ;-)

Also the DS301_profile.xml has some accessType="cons"..

**Comment by robincornelius** [comment]
the whole const/const ro etc is a bit of a mess. There is a little bit of a mis matching between canopen node and the true eds specification.  Probably the mapping logic needs a little better fixing up. Also with canopen node you can put variables in eeprom/ram or rom and clearly a rom variable cannot be anything but ro/const etc
