### ISSUE TITLE
When changing datatype of parent SDO, propagate to all children

### ISSUE THREAD

**Issue by s-fuchs** [robincornelius/libedssharp#25]
because one can not change datatype of children ;-)

**Comment by robincornelius** [comment]
Need to be careful, Array objects always have the first child as a U8 subindex parameter but the rest of cause must match the parent. Rec objects are just structures so this does not apply.

I'll check the propagation code to ensure that datatype is also propagated for array objects

**Comment by robincornelius** [comment]
Ok i think this is a UI bug only, when clicking on a array sub object it is attempting to update the combo box to what ever the parent data type is *but* when the combobox is disabled it will not update its display value.
