### ISSUE TITLE
Feature: 'save all' Button

### ISSUE THREAD

**Issue by s-fuchs** [robincornelius/libedssharp#33]
Hi,
the editor is taking great shape, very nice!

One minor request: After editing, i have to save all three components (device.xml, eds and .c/.h), so doing this with just one click would be very handy.

Thanks!

**Comment by robincornelius** [comment]
Yes +1

Its been driving me nuts as well, but i've been too busy using the tool to fix it for a few days

**Comment by robincornelius** [comment]
Ok its done and combined with some other stuff to try to warn of unsaved changes. I'll give it some serious testing tomorrow but any feedback welcome. But please backup your files! just incase i've done something really stupid and try to overwrite the wrong one with the wrong data
