### ISSUE TITLE
PDO Map Options

### ISSUE THREAD

**Issue by m1ke02** [robincornelius/libedssharp#36]
PDO Map combo does not have "TPDO" and "RPDO" options.
upd: Also COS flag cannot be set. After pressing save button it returns to unchecked state.

**Comment by robincornelius** [comment]
Are you running the prebuilt release program or are you running the code from git? I ask because #31 was the COS flag could not be set and this I thought was fixed in git.

**Comment by m1ke02** [comment]
I'm running the prebuilt release. Sorry, i didn't notice #31.
