### ISSUE TITLE
Number of RPDO's

### ISSUE THREAD

**Issue by jimlittlefield** [robincornelius/libedssharp#40]
I added 17 additional RPDOs using the Rx PDO Mapping tab (right click -> insert PDO), then verified that the additional RPDO communications/mapping objects were listed in the Object Dictionary.     Saved settings and returned to the Device Info Tab where the Number of RPDOs remained at 4 (initial value).    Exporting the c/h files does produce the desired 21 RPDOs however.

I then went back to the RX PDO Mapping tab and mapped an object to the 5th RPDO (first 4 are already defined).     After saving the change and going back to the Device Info screen the number of RPDOs is now correctly shown as 21.

I did this starting with the _project.xml released w/ CANopenNode.

jl

**Comment by robincornelius** [comment]
Fixed in git, will be in next 0.5 release

**Comment by jimlittlefield** [comment]
Thanks Robin...you fix stuff pretty fast!
