### ISSUE TITLE
incorrect array/record entries in EDS file

### ISSUE THREAD

**Issue by HendrikY** [robincornelius/libedssharp#44]
Hello Robin,
In the EDS file generation the array/record entries are not correct if the array/record is larger then 9 entries.
I've solved this by changing the line:
  writer.WriteLine(string.Format("[{0:X}sub{1}]", index,subindex));
to:
  writer.WriteLine(string.Format("[{0:X}sub{1:X}]", index,subindex));
('write'-routine in eds.cs).

br. Hendrik.

**Comment by robincornelius** [comment]
Thanks, a simple hex/decimal fomatting mistake. I will update this and push a new set of commits
