### ISSUE TITLE
Device Info saving

### ISSUE THREAD

**Issue by martinwag** [robincornelius/libedssharp#48]
Hi,

when saving  info page to .eds/xml, some info is not exported/saved.

Field:                                 ok in .eds export;        saved in .xml
Product number               yes                            no
Vendor number                yes                            no

Description                      yes                            no
Creation Date/Time         no                              yes (auto filled)
Modification D/T              no                             yes (auto filled)
Modified by                     yes                            no
Baudrates                        yes                            no
Device settings                yes                            no

I've had a go at fixing this, but wasn't too successfull at finding all the neccessary places in the code. I'm more into embedded systems that GUI design :-)

**Comment by martinwag** [comment]
I've tried this using GIT 8f9e79617fc6685693e613efc47fffe0df2c75cc

**Comment by robincornelius** [comment]
I'll take a look at those fields, They were saving at one point so probably a regression as things were moved and updated.

The git link you pasted is one to an old commit of mine?

**Comment by martinwag** [comment]
Right now, it's the most recent commit.
