### ISSUE TITLE
EDS generation failes because of comments are null

### ISSUE THREAD

**Issue by s-fuchs** [robincornelius/libedssharp#5]
Hi Robin ,
first of all: thanks for all the work, great editor!
I'm happy to see some progress :+1: 

I tried to generate an EDS file (in debug mode) and it failed because the comments object is null. Also i was not able to find a way to enter a comment to fill in this object?

I fixed it with a "if (comments==null) return;" in line 402 in eds.ch, but i think you can work out a better solution.

Thanks!

Simon

**Comment by robincornelius** [comment]
Thanks for another catch, I've used your suggestion and also a check to see if there is a not null comment block but 0 lines. Comment block is optional per DSP306 so its ok to not write it if its empty.

Fixed in in 5a46b12ea8c5aa9cb9a73e505d3ac429dce717b8
