### ISSUE TITLE
0.5 beta: c_names does wired things when generating c/h-files

### ISSUE THREAD

**Issue by s-fuchs** [robincornelius/libedssharp#58]
Hi Robin, thanks for the work in the past weeks, it gets solid!

I guess this has to do with commit 61c2b84, some observations:
- some strings are duplicated 
- single letters/digits are omited
- sometimes everything is lowercase

Examples from my .c file before/after 0.5 beta:
```c
before:  {(void*)&CO_OD_ROM.RPDOCommunicationParameter[1].COB_IDUsedByRPDO, 0x8d, 0x4 },
after:   {(void*)&CO_OD_ROM.rpdocommunicationparameter[1].cob_idusedbyrpdo, 0x8d, 0x4 },

before: {(void*)&CO_OD_ROM.TPDOMappingParameter[0].mappedObject4, 0x8d, 0x4 },
after:  {(void*)&CO_OD_ROM.tpdomappingparameter[0].mappedObjectMAPPEDOBJECT, 0x8d, 0x4 },

before: {0x6040, 0x00, 0xbe, 2, (void*)&CO_OD_RAM.axle0WheelRightControlword},
after:  {0x6040, 0x00, 0xbe, 2, (void*)&CO_OD_RAM.axleAXLEWheelRightControlword},
```
Another one from .h
```c
before: #define ODA_IMU_IMUAccX 
after:  #define ODA_imu_imuaccimuacc
```

**Comment by robincornelius** [comment]
Ah meh, i rushed these last few commits out. Yes this is the most likely cause but i still can't see why. I'll have to create some test cases and maybe even reintroduce unit tests which has been along time plan
