### ISSUE TITLE
TextBox in Linux/Mono

### ISSUE THREAD

**Issue by martinwag** [robincornelius/libedssharp#60]
When changing Object Dictionary -> Description text in mono, the text gets all messed up regarding line breaks. This seems to be caused by this line:
textBox_description.Text = od.Description.Replace("\n", "\r\n"); 
inside DeviceODView.cs. All occurances of "\n" are replaced, resulting in something like "\r\r\n". I have no idea how this works on windows??

The attached patch fixes this problem for me, please have a look if this is OK and if it applies to other places in the code. 
credit for regex goes to http://stackoverflow.com/a/31056
[0001-fix-mono-linux-line-ending-messup.zip](https://github.com/robincornelius/libedssharp/files/757343/0001-fix-mono-linux-line-ending-messup.zip)

**Comment by robincornelius** [comment]
Looks good thanks, Applied patch as 5536408
