### ISSUE TITLE
Feature - OD Editor text box size alignment

### ISSUE THREAD

**Issue by martinwag** [robincornelius/libedssharp#62]
This patch makes OD name and desctiption text box size aligned to current window sizes. 
Changes:
- Elements below the decription are now anchored to bottom instead of top
- name text box is additionally aligned to right
- description text box is additionally aligned to right and bottom.

[0001-Changed-behaviour-of-name-and-description-text-fiel-.zip](https://github.com/robincornelius/libedssharp/files/757732/0001-Changed-behaviour-of-name-and-description-text-fiel-.zip)

**Comment by robincornelius** [comment]
Thanks for the continual patches ;-). It might be easier if you fork the repository in github then you can commit back to your own version and just hit "pull request" then i can just hit accept and github takes care of the rest. No need to generate and attach patch files ;-)

**Comment by robincornelius** [comment]
applied in 40154aa9be490b661d2c18634e35aabb8f6aef51
