### ISSUE TITLE
Warning object 0x1003: Arraysize vs max-subindex

### ISSUE THREAD

**Issue by trojanobelix** [robincornelius/libedssharp#63]
On exporting C files I got a warning:

_Subindex descripency on object 0x1003 arraysize: 8 vs max-subindex: 0_

But at 1003 is the Pre-defined error field where SubIndex 0 contains the Number of errors and **not**  the _max-subindex_ like the warning suggests. 

DS301 says:
 _The object entry at sub-index 00h shall contain the number of actual errors that are recorded in the array starting at sub-index 01h._

CANchkEDS has no problem with it.

**Comment by robincornelius** [comment]
Yea 0x1003 is a "special case" that behaves like no other OD entry in the fact that the sub index 0 does not reflect the maximum number of entries but the number of errors. 

The warning is too aggressive and needs to have a special work around to not warn for this OD entry as its always like this.

**Comment by trojanobelix** [comment]
Sure. It is more polish then an issue. But it might be helpful to have it on a low priority list.

**Comment by robincornelius** [comment]
I'll add the exception to the warning on the next batch of commits
