### ISSUE TITLE
Save eds, xml, device menu option problems

### ISSUE THREAD

**Issue by martinwag** [robincornelius/libedssharp#75]
Two small issues with this:
- When exporting EDS, closing and re-opening current project, the location for the EDS file is lost. This means that one has to always re-enter the EDS file path after opening a project. This works as expected with the .c/.h files.
- there is no check in the .c/.h if the files still exists -> after moving a project, exporting leads to a crash.

**Comment by robincornelius** [comment]
On point #2 it should not matter that the c/h file exists, i expect what happened was it attempted to export to a folder that did not exist anymore?

**Comment by robincornelius** [comment]
499319b836608a6d81051678d309cf6fe4c16241 should fix your issues

**Comment by martinwag** [comment]
#1 fixed, thanks!
#2 doesn't crash anymore, but doesn't give an error either. It seems to do nothing? Would using relative paths be a solution for this?

**Comment by robincornelius** [comment]
Closing as my first fix and your PR should have taken care of everything here
