### ISSUE TITLE
EDS data placent to wrong memory

### ISSUE THREAD

**Issue by on4ip** [robincornelius/libedssharp#77]
Hi. Today I create oun EDS file and find some bug.
If I choose ROM for OD field and save EDS file In Note PAd i see that ;StorageLocation=ROM.
But after Loading EDS to editor i see that field located in RAM. 
If i save XML and load it again filed in Editor the field placement are correct.
It look like some errors during parsing from EDS file.

**Comment by on4ip** [comment]
In EDITOR
![editor view](https://cloud.githubusercontent.com/assets/22025334/25088494/cb381940-2387-11e7-8c6d-f30752ce695f.PNG)
IN EDS
![eds file](https://cloud.githubusercontent.com/assets/22025334/25088495/cb3ba10a-2387-11e7-91bc-c70518843d58.PNG)

**Comment by robincornelius** [comment]
Hi i'll take a look at that.

The EDS file does not really support the StorageLocation it is added in as a comment in the eds (hence the line starting with a ; ) but this still should export the correct data. No other program can support reading this field from eds as its not part of the standard.

The XML format is native to this program and stores all the info we have.

**Comment by robincornelius** [comment]
https://github.com/robincornelius/libedssharp/commit/d4b4bcd873b4c0540eafa99370715f28e33b5a0e should fix it. its currently on the experimental branch but ill test it when i have time and merge to master

**Comment by robincornelius** [comment]
Merged with master
